# Generated by Django 5.1.1 on 2024-10-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobannounce",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
